### ISSUE TITLE
checkstyle: NewlineAtEndOfFile errors with vanilla Git config on Windows

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#191] opened 2016-12-07 07:45 UTC
Checkstyle errors on Windows only when running `gradle checkstyleMain`. Most likely a line endings configuration problem:
```
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\MainApp.java:0: File does not end with a newline. [NewlineAtEndOfF
ile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\ComponentManager.java:0: File does not end with a new
line. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\Config.java:0: File does not end with a newline. [New
lineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\EventsCenter.java:0: File does not end with a newline
. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\GuiSettings.java:0: File does not end with a newline.
 [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\LogsCenter.java:0: File does not end with a newline.
[NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\Messages.java:0: File does not end with a newline. [N
ewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\UnmodifiableObservableList.java:0: File does not end
with a newline. [NewlineAtEndOfFile]
```

cc @m133225

**Comment by m133225** [comment] 2016-12-07 07:51
Is this on the master branch? Can't seem to reproduce this.

**Comment by pyokagan** [comment] 2016-12-07 07:58
> Does this happen on the master branch? Can't seem to reproduce this.

Yeah, master branch. Do you have `core.autocrlf` switched on in Git?

FWIW, this patch fixes it for me. The default value for `lineSeparator` is the system default, which on Linux is LF while on Windows is CRLF. Since this repo uses LF line endings, it makes sense that the check fails on Windows.
```diff
diff --git a/config/checkstyle/checkstyle.xml b/config/checkstyle/checkstyle.xml
index c786caa..81f19bc 100644
--- a/config/checkstyle/checkstyle.xml
+++ b/config/checkstyle/checkstyle.xml
@@ -14,7 +14,9 @@
     <!-- Checks that there are no tab characters in the file. -->
   </module>

-  <module name="NewlineAtEndOfFile"/>
+  <module name="NewlineAtEndOfFile">
+    <property name="lineSeparator" value="LF" />
+  </module>

   <module name="RegexpSingleline">
     <!-- Checks that FIXME is not used in comments.  TODO is preferred. -->

```

**Comment by m133225** [comment] 2016-12-07 08:12
Hmm, then I think switching on `core.autocrlf` should be the way Windows users work on this repo since it is meant to work on both Windows and Linux/Mac platforms 😛

**Comment by pyokagan** [comment] 2016-12-07 08:30
> Hmm, then I think switching on core.autocrlf should be the way Windows users work on this repo

I disagree for the following reasons:

1. The default `core.autocrlf` config value is `false`. This means that if we require all Windows developers to set `core.autocrlf` to true, they will need to explicitly configure this as an additional setup step. (And we'll need to teach developers how to set per-project git config, ugh ;-) )

2. CRLF conversion is an additional translation layer, which means that it could be an additional source of problems. According to the [git-config man page](https://git-scm.com/docs/git-config#git-config-coresafecrlf), CRLF conversion might corrupt data. There have also been CRLF bugs in the past. It may not be a problem now, but it may in the future ;-)

    > CRLF conversion bears a slight chance of corrupting data. When it is enabled, Git will convert CRLF to LF during commit and LF to CRLF during checkout. A file that contains a mixture of LF and CRLF before the commit cannot be recreated by Git. For text files this is the right thing to do: it corrects line endings such that we have only LF line endings in the repository. But for binary files that are accidentally classified as text the conversion can corrupt data.

But actually, I think the best solution is to just accept both LF and CRLF. Something like this:
```diff
diff --git a/config/checkstyle/checkstyle.xml b/config/checkstyle/checkstyle.xml
index c786caa..81f19bc 100644
--- a/config/checkstyle/checkstyle.xml
+++ b/config/checkstyle/checkstyle.xml
@@ -14,7 +14,9 @@
     <!-- Checks that there are no tab characters in the file. -->
   </module>

-  <module name="NewlineAtEndOfFile"/>
+  <module name="NewlineAtEndOfFile">
+    <property name="lineSeparator" value="lf_cr_crlf" />
+  </module>

   <module name="RegexpSingleline">
     <!-- Checks that FIXME is not used in comments.  TODO is preferred. -->
```
This way, Windows users can set `core.autocrlf` as they wish.

**Comment by m133225** [comment] 2016-12-07 08:53
The problem with this is that when Windows users make changes to the repository and doesn't set autocrlf to true, CRLFs may be committed to the repository. This will in turn make the whitespaces inconsistent. But this is a separate issue.

I guess accepting both LF and CRLF for the checkstyle sounds reasonable, but reviewers have to ensure that the committed code does not contain CLRFs.

**Comment by damithc** [comment] 2016-12-07 09:03
Any way to enforce it using CI (instead of reviewer checking manually), e.g. using checkstyle?

**Comment by m133225** [comment] 2016-12-07 09:08
The current way enforces that, but it will cause checkstyle to fail on Windows since the local files may contain CLRFs.

**Comment by damithc** [comment] 2016-12-07 09:16
I see. I'm hoping there is a standard solution to this as this is applicable to most non OS-specific OSS projects.

**Comment by pyokagan** [comment] 2016-12-07 10:44
@damithc 
> Any way to enforce it using CI (instead of reviewer checking manually)

One way could be to introduce a `checkstyleCI` gradle task that runs additional stricter checkstyle checks. Something like this:

```diff
diff --git a/.travis.yml b/.travis.yml
index 5a47b04..12ec9fd 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,7 +2,7 @@ language: java
 matrix:
   include:
     - jdk: oraclejdk8
-script: travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls -i
+script: travis_retry ./gradlew clean checkstyleMain checkstyleTest checkstyleCI headless allTests coverage coveralls -i
 before_install:
           - "export DISPLAY=:99.0"
           - "sh -e /etc/init.d/xvfb start"
diff --git a/build.gradle b/build.gradle
index 74669b8..2e9586f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -120,6 +120,13 @@ tasks.coveralls {
     onlyIf { System.env.'CI' }
 }
 
+task checkstyleCI(type: Checkstyle) {
+    description = 'Additional checkstyle checks for continuous integration.'
+    configFile = file('config/checkstyle/checkstyle-ci.xml')
+    classpath = tasks.checkstyleMain.classpath + tasks.checkstyleTest.classpath
+    source = tasks.checkstyleMain.source + tasks.checkstyleTest.source
+}
+
 class AddressBookTest extends Test {
     public AddressBookTest() {
     	  forkEvery = 1
diff --git a/config/checkstyle/checkstyle-ci.xml b/config/checkstyle/checkstyle-ci.xml
new file mode 100644
index 0000000..98e97eb
--- /dev/null
+++ b/config/checkstyle/checkstyle-ci.xml
@@ -0,0 +1,16 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE module PUBLIC
+    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
+    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
+
+<!--
+    Additional checks for CI
+-->
+
+<module name="Checker">
+  <!-- Stricter line ending check that forbids windows line endings -->
+  <module name="RegexpMultiline">
+    <property name="format" value="\r\n"/>
+    <property name="message" value="Do not use Windows line endings"/>
+  </module>
+</module>
diff --git a/config/checkstyle/checkstyle.xml b/config/checkstyle/checkstyle.xml
index c786caa..c714340 100644
--- a/config/checkstyle/checkstyle.xml
+++ b/config/checkstyle/checkstyle.xml
@@ -14,7 +14,9 @@
     <!-- Checks that there are no tab characters in the file. -->
   </module>
 
-  <module name="NewlineAtEndOfFile"/>
+  <module name="NewlineAtEndOfFile">
+    <property name="lineSeparator" value="lf_cr_crlf"/>
+  </module>
 
   <module name="RegexpSingleline">
     <!-- Checks that FIXME is not used in comments.  TODO is preferred. -->
```

**Comment by pyokagan** [comment] 2016-12-07 10:53
@m133225 
> The problem with this is that when Windows users make changes to the repository and don't set autocrlf to true (or at least input), CRLFs may be committed to the repository. This will in turn make the whitespaces inconsistent. But this is a separate issue.

Yep, I agree this is a problem and should be caught at the stage when the PR is submitted.
 I also agree that this is a separate issue. (One possible solution in https://github.com/se-edu/addressbook-level4/issues/191#issuecomment-265415216)

> I guess accepting both LF and CRLF for the checkstyle sounds reasonable,

So for this issue I guess the diff in https://github.com/se-edu/addressbook-level4/issues/191#issuecomment-265386686 is an acceptable solution?

**Comment by damithc** [comment] 2016-12-07 13:39
I'm ok to give it a try. It's not cast in stone, so we can revert back if it causes too many problems for Windows users.

**Comment by pyokagan** [comment] 2016-12-07 16:27
Okay, we should definitely change the checkstyle config to accept LFs at least, and not be dependent on platform.

Consider the use case where a developer, instead of using Git, uses Github's [Download as ZIP](https://github.com/se-edu/addressbook-level4/archive/master.zip) functionality. Or downloads Github's automatically generated ZIP files from the [releases page](https://github.com/se-edu/addressbook-level4/releases). Since Github does not perform any line-ending conversion, the developer will get these checkstyle errors. `core.autocrlf` won't save the developer here :-)

Now, whether developers should be converting line endings on their own working copy or not is another issue. For now, let's give developers the option of choosing LF or CRLF as their line endings on their working copy, as long as they ensure their commits all use LF.

**Closed** 2016-12-10 14:52 UTC
