### ISSUE TITLE
Browser panel is not hidden after clear command

### ISSUE THREAD

**Issue by yunpengn** [se-edu/addressbook-level4#740] opened 2017-11-19 17:08 UTC
After using `clear` command, the browser panel is still showing the google search page of the previously selected person. Is it more reasonable if it is hidden (since that person being searched is already removed)?

![image](https://user-images.githubusercontent.com/18503402/32993165-459073de-cd8f-11e7-86b2-62b9940313cd.png)

**Comment by pyokagan** [comment] 2017-11-20 07:09
Duplicate of #731. Let's take the discussion there instead.

**Closed by pyokagan** 2017-11-20 07:09 UTC
