### ISSUE TITLE
HelpWindow: help window stays open even after exiting by clicking the close button

### ISSUE THREAD

**Issue by vivekscl** [se-edu/addressbook-level4#826] opened 2018-02-11 10:46 UTC
This should not be the case as closing the app should close every other window related to it.

Edit: Likely to happen on certain operating systems only. So far, it seems to be happening on Linux.

**Comment by Zhiyuan-Amos** [comment] 2018-02-11 12:37
On MacOS: When both the application & Help Window are full screen, executing `ExitCommand` closes both the application & Help Window.

**Comment by yamgent** [comment] 2018-02-12 02:50
I cannot reproduce this bug on Windows 10.

**Comment by yamgent** [comment] 2018-02-12 03:08
I just tried it out on Linux and didn't face any issue... can you tell us what you did step by step? :P

I was able get the `HelpWindow` closed if I do the following:
1. Use the Help menu to open `HelpWindow` (this is to circumvent the bug in #727).
1. Ensure that both windows are full-screened.
1. Execute `exit`.

**Comment by vivekscl** [comment] 2018-02-12 04:12
The steps to reproduce the error is the following:

1. Use any method to open the `HelpWindow`
2. Ensure both screens are full-screened
3. And then close using the `x` button at the top right hand corner

**Comment by yamidark** [comment] 2018-02-13 06:26
I'm able to reproduce the bug on Windows 10 though:
- open help window through any methods, click the close button, help window stays.
- open help window through `F1` or menu button, then executing `exit` will close the help window.
- open help window through `help`, calling `exit` does not even close the app, until the help window is closed.

**Comment by yamgent** [comment] 2018-02-13 11:23
> Typing exit does close the HelpWindow automatically.
> The steps to reproduce the error is the following:
> 
> 1. Use any method to open the HelpWindow
> 1. Ensure both screens are full-screened
> 1. And then close the app using the x button at the top right-hand corner

Ah okay, I can now reproduce this issue. In fact, you don't even need the screen to be full in order to reproduce this bug.

I took a quick look at the codebase, and I think the reason is because `MainWindow` is not associated with `HelpWindow` in any way, so closing `MainWindow` will not affect `HelpWindow` (the `exit` command does not have this issue because it closes the entire application, rather than just `MainWindow`).

I see two different possible ways of solving this:

1. Just make `MainWindow` call `MainWindow#handleExit` when closing the window, so that the effect is same as executing `ExitCommand`, or
1. Associate `MainWindow` with `HelpWindow`, by setting `MainWindow` as `HelpWindow`'s owner. I.e. (Note the code is not perfect, and it introduces an annoying behaviour that makes `HelpWindow` not selectable on the taskbar).
```diff
diff --git a/src/main/java/seedu/address/ui/MainWindow.java b/src/main/java/seedu/address/ui/MainWindow.java
index 20ad5fee..ce5f29c4 100644
--- a/src/main/java/seedu/address/ui/MainWindow.java
+++ b/src/main/java/seedu/address/ui/MainWindow.java
@@ -166,6 +166,7 @@ public class MainWindow extends UiPart<Stage> {
     @FXML
     public void handleHelp() {
         HelpWindow helpWindow = new HelpWindow();
+        helpWindow.getRoot().initOwner(this.getRoot()); // note: on Windows, HelpWindow is not visible on the taskbar.
         helpWindow.show();
     }
```

**Closed** 2018-03-02 15:56 UTC
Labels: a-GUI, c.Bug
