### ISSUE TITLE
Open help window using help command will block subsequent inputs of command box

### ISSUE THREAD

**Issue by yunpengn** [se-edu/addressbook-level4#739] opened 2017-11-19 16:52 UTC
1. Tried to open the help window (the built-in user guide) with `help` command, by typing `help` in the command box.
2. The help window will open normally, but there is no result message displayed in the result display area.
![image](https://user-images.githubusercontent.com/18503402/32992951-2e41d02c-cd8c-11e7-9265-a94d394dc298.png)
3. Type in any command into the command box, for example `select 1`, the command will be blocked (I think it is because the application is waiting for `help` command to finish, the `help` command has not finished yet since the help window is not closed yet)
4. After close the help window, the result message would be `Opened help window.`, which is the result message of `help` command; however, `select 1` has taken effect as well.

Suspect this issue is caused because the logic component is single-thread, similar to the concept of **blocking** and **asynchronous** in Node.js, not sure how we can fix this Java.

However, it seems that this bug does not occur if I open the help window by mouse click or press `F1` key. So maybe a possible fix is: _we can try to raise an event to simulate pressing the `F1` key or mouse click the menu?_

**Comment by liliwei25** [comment] 2017-11-19 17:47
I think the bug has already been spotted here: #727

**Comment by Zhiyuan-Amos** [comment] 2017-11-20 00:44
Thanks both @yunpengn & @liliwei25, yes it's a duplicate of #727, closing this :)

**Closed by Zhiyuan-Amos** 2017-11-20 00:44 UTC
