### ISSUE TITLE
Revamp sleep() for Gui tests

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#502] opened 2017-06-16 07:38 UTC
The current `GuiRobot` sleeps at a random interval. Most of the sleeps are purely for us human to examine the effects of the test, and therefore do not need to be paused when doing headless mode.

Some of the pauses are also unnecessary as the application will have sufficient time to continue the operation after GUI actions such as key presses.

Let's revamp sleeping in Gui tests by:
* Adding a pauseForHuman(int) to indicate that such delays are for humans but are not required for the tests to succeed.
* Adding appropriate checks to the application state for operations that do need to wait for certain events in the application to happen.
* Removing unnecessary delays.

**Comment by pyokagan** [comment] 2017-06-16 08:33
Somewhat a duplicate of https://github.com/se-edu/addressbook-level4/issues/139

**Closed** 2017-06-27 00:18 UTC
