### ISSUE TITLE
Ui: PersonListPanel default background color does not fit into the dark theme style

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#723] opened 2017-10-12 04:07 UTC
Upon using a find command, if the result is not found, it shows a white color list view pane which does not match our Dark Theme style, let's fix it by including the background color field in our DarkTheme.css file.

**Comment by yamgent** [comment] 2017-10-12 15:44
> let's fix it by including the background color field in our DarkTheme.css file.

Does it work? If my memory serves me right, I think @MightyCupcakes did something similar and couldn't get it to work.

**Comment by eugenepeh** [comment] 2017-10-13 01:23
yup, I fixed it for 2 of the teams during 2103 tutorial class.

**Comment by damithc** [comment] 2017-10-13 01:42
> yup, I fixed it for 2 of the teams during 2103 tutorial class.

It's good if we can share that info with the whole class in some way

**Comment by eugenepeh** [comment] 2017-10-13 02:36
@damithc got it, will post it as an issue on the 2103 github forum

**Comment by pyokagan** [comment] 2017-12-01 04:53
Duplicate of #415

**Closed** 2017-12-01 04:53 UTC
