### ISSUE TITLE
Discrepancy when undoing/redoing for Edit Command

### ISSUE THREAD

**Issue by liliwei25** [se-edu/addressbook-level4#741] opened 2017-11-19 17:43 UTC
When editing the name of a `Person` after the `find` command, it works perfectly fine. However, after the edit is done and the list is automatically refreshed, undoing and redoing the same command will result in a discrepancy. 

Steps to reproduce:
1. `find bernice`
2. `edit 1 n/test`
3. `undo`
4. `redo`

Screenshots:

1. 
![image](https://user-images.githubusercontent.com/22389228/32993492-ebc61e44-cd93-11e7-9a0a-70a0b8018cb6.png)
2. 
![image](https://user-images.githubusercontent.com/22389228/32993502-0937150a-cd94-11e7-8fcc-201e644ba9fa.png)
3. 
![image](https://user-images.githubusercontent.com/22389228/32993509-27e2272e-cd94-11e7-98c4-57840259518c.png)
4.
![image](https://user-images.githubusercontent.com/22389228/32993510-32bbba8e-cd94-11e7-9bee-c87f2b7df702.png)

**Comment by Zhiyuan-Amos** [comment] 2017-11-20 00:43
Closing this as it's a duplicate of #737 :)

**Closed by Zhiyuan-Amos** 2017-11-20 00:43 UTC
