### ISSUE TITLE
Repetitive prefixes in the add command do not show invalid format error

### ISSUE THREAD

**Issue by danielbrzn** [se-edu/addressbook-level4#745] opened 2017-11-21 09:51 UTC
For example, the following command will execute correctly  even though it contains multiple valid prefixes.

`add n/Michael p/98765432 p/12345678 e/michael@hotmail.com a/michael gold street a/bronze street p/00000000`

Michael will be added, but his address will be `bronze street` and his phone number will be `00000000`.

![image](https://user-images.githubusercontent.com/251231/33065817-98eacb6e-cee4-11e7-9bf2-4f76e91f1819.png)

Would this be an extension of issue #444?

**Comment by pyokagan** [comment] 2017-11-21 10:00
Duplicate of #206 
Let's take the discussion there.

**Closed** 2017-11-21 10:00 UTC
