### ISSUE TITLE
AddCommandParser accepts invalid command format

### ISSUE THREAD

**Issue by teclu** [se-edu/addressbook-level4#738] opened 2017-11-19 16:05 UTC
![image](https://user-images.githubusercontent.com/27724529/32992511-89c230a0-cd86-11e7-8a63-7a55577521da.png)

Typing "add **formattingProblem123** n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney" should generate an "**Invalid command format!**" message, since we are not adhering to the correct format of the command.

However, this does not trigger the error message, and the person is successfully added instead (_does not generate any problems though_)

**Comment by pyokagan** [comment] 2017-11-19 16:20
Thanks, I've reproduced this. Seems to be a side effect of 17aceb2eb3fb492aa8541c6224d530a2836b3777

PRs welcome :-)

**Comment by pyokagan** [comment] 2017-11-19 16:48
Marking this as first timers. I think the only fix we need to do is to ensure that `argMultimap.getPreamble()` is empty in `AddCommand`, as well as adding a test for this.

**Closed** 2017-12-24 09:10 UTC
Labels: a-Parsing, c.Bug, d.FirstTimers, help wanted
