### ISSUE TITLE
HelpWindow: Gibberish text (Mac only)

### ISSUE THREAD

**Issue by chao1995** [se-edu/addressbook-level4#374] opened 2017-03-30 16:57 UTC
<img width="1280" alt="screen shot 2017-03-31 at 12 47 49 am" src="https://cloud.githubusercontent.com/assets/7572632/24516014/e0b3dcbc-15ab-11e7-8971-af92e304d23c.png">

Tested on java version "1.8.0_121" and Mac OS version "10.12.4"

It turns out to be a bug in JavaFx WebView on Mac, it tries to load some fonts locally and is disallowed (explained in [this StackOveflow answer](http://stackoverflow.com/a/42375360/3522482)). Also as pointed out in the related [open JDK issue](https://bugs.openjdk.java.net/browse/JDK-8175802?focusedCommentId=14055132&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14055132), this is fixed in Java 9 early access version (9-ea+148)

Some possible walk-arounds:

1. change GitHub Pages theme. For example, [MERLOT THEME](https://github.com/pages-themes/merlot) works.
1. programatically [insert another `<style>` tag into the `WebView` html](http://stackoverflow.com/questions/41952734/javafx-webview-font-issue-on-mac#comment71578136_41952734) to change the font used.
1. revert [this PR](https://github.com/se-edu/addressbook-level4/pull/259)

There is still possibility that if we download open sans font as a `.tff` file and add to the app, then load it in JavaFX at runtime, it will display the font correctly, but this approach is relatively more complicated and not yet tried out.

**Comment by MightyCupcakes** [comment] 2017-03-31 00:46
I don't think downloading the font helps as the `WebView` cannot be styled by our CSS, rather the webpage's CSS

**Comment by chao1995** [comment] 2017-03-31 03:41
@MightyCupcakes I agree it maybe doesn't help. But actually we can style `WebView`'s content using our CSS, i.e. we can programatically change the font used in the html by adding some additional style tag.

**Comment by damithc** [comment] 2017-03-31 04:04
Any other themes that work?

**Comment by chao1995** [comment] 2017-04-01 04:14
> Any other themes that work?

Yes, actually out of the default 12 themes provided in GitHub Pages settings, only "Cayman" doesn't work. The rest are all fine.

**Comment by damithc** [comment] 2017-04-01 06:09
@chao1995 We chose Cayman because it gives a clean dev/user guide pdf file that can be used for CS2101.
Can you check if [semester fork](https://github.com/nus-cs2103-AY1617S2/addressbook-level4) is affected? If not, we can leave this alone until we move to asciidoc.

**Comment by chao1995** [comment] 2017-04-01 08:35
> Can you check if semester fork is affected?

I cloned the repo, confirmed that the fork is affected.

**Comment by damithc** [comment] 2017-04-01 09:40
> I cloned the repo, confirmed that the fork is affected.

I see. In that case I'll inform CS2103 teaching team that students can fix it by changing the theme.

**Comment by damithc** [comment] 2017-06-05 04:54
Does this persist even after converting to asciidocs?

**Comment by chao1995** [comment] 2017-06-05 05:05
@damithc Just updated to the latest commit, but now I get a 404 due to this broken link: https://se-edu.github.io/addressbook-level4/docs/UserGuide.html.

The link should actually be https://se-edu.github.io/addressbook-level4/UserGuide.html (without the docs) @yamgent for your notice.

However, the gibberish text issue still persists.

<img width="1015" alt="screen shot 2017-06-05 at 1 04 01 pm" src="https://cloud.githubusercontent.com/assets/7572632/26771249/abfd1876-49ef-11e7-8467-ed9ae5ae74e0.png">

**Comment by yamgent** [comment] 2017-06-05 05:52
> The link should actually be https://se-edu.github.io/addressbook-level4/UserGuide.html (without the docs) @yamgent for your notice.

Thanks for the notice, will raise this issue if I still haven't fix the offline docs issue.

**Comment by yamgent** [comment] 2017-06-06 01:13
@limmlingg Could you possibly look at some other asciidoctor themes that uses a different font without it becoming gibberish?

**Comment by limmlingg** [comment] 2017-07-13 06:01
Apparently, this is fixed in JDK 9: https://bugs.openjdk.java.net/browse/JDK-8175802

Refer to the comments at the bottom of the page.

**Comment by damithc** [comment] 2017-09-27 08:38
> Could you possibly look at some other asciidoctor themes that uses a different font without it becoming gibberish?

Perhaps we should give this a try? I don't think we can upgrade to jdk 9.0 at this point.

**Comment by damithc** [comment] 2017-09-27 08:39
BTW, does this affect all Mac users?

**Comment by limmlingg** [comment] 2017-09-27 12:10
> Perhaps we should give this a try? I don't think we can upgrade to jdk 9.0 at this point.

[As @chao1995 mentioned](https://github.com/se-edu/addressbook-level4/issues/374#issuecomment-290893468), all other default themes for GitHub Pages work.

**Comment by damithc** [comment] 2017-09-28 00:15
> As @chao1995 mentioned, all other default themes for GitHub Pages work.

But we are using asciidoc, so we can't use the themes provided by GitHub, right?

**Comment by damithc** [comment] 2017-10-02 01:15
Wait, the original issue was supposedly caused by a specific font in a specific GitHub pages theme. The asciidoc theme has the same font?

**Comment by yamgent** [comment] 2017-10-02 02:12
If I didn't read the bug report wrongly, it seems to be an issue of how JavaFx tries to load fonts without a proper family name, So it could be happening to groups of fonts, rather than it being the issue of a particular font.

Since now we have control of the [css](https://github.com/se-edu/addressbook-level4/blob/master/docs/stylesheets/asciidoctor.css) file, perhaps a Mac user can try and experiment around with the file to see which fonts won't cause that behaviour.

**Comment by limmlingg** [comment] 2017-10-02 02:21
> perhaps a Mac user can try and experiment around with the file to see which fonts won't cause that behaviour.

Paging @Zhiyuan-Amos

**Comment by Zhiyuan-Amos** [comment] 2017-10-02 02:32
won't work on this unless someone guides me with css (i.e. just tell me which line to edit).

**Comment by pyokagan** [comment] 2018-12-12 14:37
We'll get this issue again when we downgrade to JDK8.

Reopening so I don't forget.

**Comment by pyokagan** [comment] 2018-12-12 14:40
> Since now we have control of the css file, perhaps a Mac user can try and experiment around with the file to see which fonts won't cause that behaviour.

And yeah, we should workaround it by doing this.

**Comment by pyokagan** [comment] 2019-01-18 13:38
Couldn't reproduce this issue anymore on jdk1.8.0_201 on macOS 10.14.2.

Searched around, [turns out the fix was backported into JDK 8u152](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8088205), so we're fine now.

![screenshot 2019-01-18 at 9 31 35 pm](https://user-images.githubusercontent.com/109479/51389962-decc7200-1b68-11e9-8fc6-bbd266819e29.png)

**Closed by pyokagan** 2019-01-18 13:38 UTC
Labels: a-GUI, c.Bug
